sudo: false
language: r
cache: packages

addons:
  apt:
    packages:
      - libpoppler-cpp-dev
      - ghostscript

r_github_packages:
  - r-lib/covr
      
after_success:
  - Rscript -e 'covr::codecov()'
